xblock-free-text-response | Drop py3.8 support | replace pkg_resource with importlib.resources
openedx/xblock-free-text-response pull request #192
Opened 2024-09-11 11:20 UTC by OmerBhatti

- Drop Py3.8 support
 - Upgrade python requirements
 - Replace pkg_resources lib with importlib.resources

**Ticket:** [Move on from deprecated pkg_resources api](https://github.com/openedx/xblock-sql-grader/issues/176)

Followed migration guide: https://importlib-resources.readthedocs.io/en/latest/migration.html

**Testing:**
I have tested the changes with following steps:

 - Install xblock-free-text-response into xblock-sdk
 - Test xblock-free-text-response functionality and not crashes
 - Run tox tests

## Screenshots
<img width="1637" alt="image" src="https://github.com/user-attachments/assets/10a49789-6d2f-46fc-890a-05b020a28f89">

2024-09-11 11:20 UTC, openedx-webhooks commented
Thanks for the pull request, @OmerBhatti!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads


#### :radio_button: Submit a signed contributor agreement (CLA)

:warning: We ask all contributors to the Open edX project to submit a [signed contributor agreement](https://openedx.org/cla) or indicate their institutional affiliation.
Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md) file for more information.

If you've signed an agreement in the past, you may need to re-sign.
See [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/) for details.

Once you've signed the CLA, please allow 1 business day for it to be processed.
After this time, you can re-run the CLA check by adding a comment below that you have signed it.
If the CLA check continues to fail, you can tag the `@openedx/cla-problems` team in a comment for further assistance.

<!-- comment:no_cla -->




#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?



This repository is currently unmaintained.

To get help with finding a technical reviewer, tag the community contributions project manager for this PR in a comment and let them know that your changes are ready for review:

1. On the right-hand side of the PR, find the Contributions project, click the caret in the top right corner to expand it, and check the "Primary PM" field for the name of your PM.
2. Find their GitHub handle [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3548807177/Community+Contributions+Project+Manager#Current-OSPR-Project-Managers).


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-09-24 15:16 UTC, e0d commented
@OmerBhatti looks like there are some failing checks, can you have a look.

2024-09-30 13:15 UTC, farhan requested changes

2024-09-30 13:29 UTC, OmerBhatti commented on .github/workflows/ci.yml
>          - '3.11'
added 3.12, bumped the version too and added changelogs

2024-09-30 14:30 UTC, farhan requested changes

2024-09-30 14:30 UTC, farhan commented on freetextresponse/__init__.py
> +__version__ = "4.2.0"
Please update it to `5.0.0`

2024-09-30 14:30 UTC, farhan commented on CHANGELOG.md
> +## Version 4.2.0
Please update it to `5.0.0`

2024-10-01 08:20 UTC, farhan approved these changes

2024-10-25 16:44 UTC, feanil approved these changes

2024-10-25 16:45 UTC, feanil commented
Looks like it has some quality failures that need to be resolved.

2025-01-07 05:27 UTC, ttqureshi commented
@farhan please assign this to me.

2025-01-07 09:29 UTC, farhan commented
> @farhan please assign this to me.

@ttqureshi, you can create a new branch, address the failures, and submit a new PR to replace this one. Once done, you can close the existing PR.
**Note:** @OmerBhatti is no longer with Arbisoft and seems to have discontinued work on this PR.

2025-01-07 17:50 UTC, feanil commented
In that case, let's just close this PR and we can just wait for the new one from @ttqureshi when it's ready.

2025-01-07 17:50 UTC, closed without merging